#WARNING! This docker-compose file is insecure. But it's good as an instruction which ports have to be used.
#You don't need use it, the default and secure docker-compose.yml is available.
version: '2'
services:

  1c.local:
    image: ethi0/1c_server:latest
    volumes_from:
    - data
    volumes:
    - /etc/localtime:/etc/localtime:ro
    ports:
    - 1540-1541:1540-1541
    - 1560-1591:1560-1591
    restart: always
    container_name: 1c.local
    networks: 
      net:
        ipv4_address: 172.18.0.2
    hostname: 1c.local
    depends_on:
    - data
    - db

  data:
    image: ethi0/1c_server_data:latest
    container_name: 1c_server_data
    volumes:
    - /var/log/1c
    - /home/usr1cv8

  db:
    image: ethi0/1c_db:latest
    container_name: 1c_db
    restart: always
    ports: 
    - 5432:5432
    - 5433:5433
    networks: 
      net:
        ipv4_address: 172.18.0.3
    hostname: 1c.db
    depends_on:
    - data
    volumes:
    - /home/usr1cv8/db_data:/data

networks:
  net:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.18.0.0/24
        gateway: 172.18.0.1
